version: '3'

dotenv:
- .env
- .env.dist

tasks:
  precheck:
    internal: true
    run: once
    cmds:
    - '[[ -z $VIRTUAL_ENV ]] && exit 1 || echo precheck pass'

  trans-def:
    deps: [extract]
    cmds:
    - task: precheck
    - python bin/trans.py dump/thingdef.json > dump/thingdef_T.csv
    - python bin/trans.py dump/stats.json > dump/stats_T.csv

  split:
    deps: [extract]
    cmds:
    - task: precheck
    - python bin/split.py

  stat:
    deps: [extract]
    cmds:
    - task: precheck
    - python bin/stat.py

  extract:
    desc: extract info from game data
    run: once
    summary: |
      Extract all Def objects from game data, including:
      * ThingDef
      * TerrainDef
      * TraitDef
      * etc.
    cmds:
    - task: precheck
    - python extract.py "$RIM_DATA_PATH" "$RIM_TRANS_PATH/Definjected" dump/data.json

  default:
    cmds:
    - task: precheck
    - echo $RIM_DATA_PATH
    - echo $RIM_TRANS_PATH
    - task: extract
    - task: trans-def
    - task: split
    - task: stat
    # - task: trans-key
